document.writeln("<header>");
document.writeln("		<div class=\'header-inner\'>");
document.writeln("			<div class=\'head-logo\'>");
document.writeln("				<a href=\'javaScript:;\'><img src=\'../img/common/logo.png\' alt=\'\'></a>");
document.writeln("			</div>");
document.writeln("			<div class=\'menu-icon\'>青蚨·一心一益关爱基金&nbsp;▼</div>");
document.writeln("		</div>		");
document.writeln("		<div class=\'shadow\'></div>		");
document.writeln("		<div class=\'menu-box\'>");
document.writeln("			<ul class=\'menu-list\'>");
document.writeln("				<li><a href=\'javaScript:;\'>首页</a></li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javaScript:;\'>关于我们</a>");
document.writeln("				<li>");
document.writeln("				    <a href=\'javaScript:;\'>心益项目</a>");
document.writeln("				    <i class=\'ico\'></i>");
document.writeln("					<div class=\'menuson\'>");
document.writeln("						<a href=\'javaScript:;\'>关注星星的孩子</a>");
document.writeln("						<a href=\'javaScript:;\'>青少年扶持计划</a>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javaScript:;\'>新闻中心</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javaScript:;\'>我的心益</a>");
document.writeln("					<i class=\'ico\'></i>");
document.writeln("					<div class=\'menuson\'>");
document.writeln("						<a href=\'javaScript:;\'>我要参与</a>");
document.writeln("						<a href=\'javaScript:;\'>我要留言</a>");
document.writeln("						<a href=\'javaScript:;\'>志愿者故事</a>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</header>");